### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_CRGoogleDrive"

### ISSUE THREAD

**Issue by DannyGlover** [CloudRail/cloudrail-si-ios-sdk#10]
Hello there.

I'm getting the following issue when integrating your SDK when building for the simulator:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CRGoogleDrive", referenced from:

Also when building for an iOS device:

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_CRGoogleDrive", referenced from:

**Comment by fel-cesar** [comment]
Hello @DannyGlover ,
* How are you integrating the SDK (cocoapods, or direct import)? 
* What version of Xcode are you using?

**Comment by DannyGlover** [comment]
Hello @fel-cesar 

I am using the framework directly (well, the static libraries, assets and headers - as the plugin I am making doesn't support using frameworks).

I'm using the latest version of Xcode: 8.0 (8A218a)

Thank you

**Comment by fel-cesar** [comment]
Ok, I will replicate the error and report about a fix for it ASAP.

Thank you for the feedback.

**Comment by DannyGlover** [comment]
@fel-cesar 

If you follow the steps below, you should be able to reproduce:

1) Link against the CloudrailSI static library directly in your build phases tab
2) Import the Headers into your project
3) Insert either line into your source file:

`id<CRCloudStorageProtocol> dropbox = [[CRDropbox alloc] initWithClientId:@"[clientID]" clientSecret:@"[clientSecret]" redirectUri:@"https://www.cloudrailauth.com/auth" state:@"state"];

id<CRCloudStorageProtocol> googleDrive = [[CRGoogleDrive alloc] initWithClientId:@"[clientID]" clientSecret:@"[clientSecret]" redirectUri:@"https://www.cloudrailauth.com/auth" state:@"state"];
`
4) Build and see the aforementioned error.

Thank you

**Comment by fel-cesar** [comment]
@DannyGlover , I couldn't reproduce the **exact** error that you are having. Your use case its the first of its kind from our side so its really important to us to help you solve it. Can you contact us through **[support@cloudrail.com](url)** so we can discuss more deeply this issue.
