### ISSUE TITLE
Login and authenticate ?

### ISSUE THREAD

**Issue by RWarnecke** [CloudRail/cloudrail-si-ios-sdk#11]
1.) I have to implement the cloudrail sdk into my app. I didn't found a way to get a response if the login was failed or successfully of my DropBox login. I did not tested it with Google Drive, OneDrive and Box I think it is the same. 

2.) On every action (upload, download and so on) my app would like to login to the cloud drive. I like the way to login one time. Can you make the authentic over the provider app and save if the app was successfully authenticate?

**Comment by fel-cesar** [comment]
Hello @RWarnecke,
 

1.  A good way get the response of success/fail would be through NSExceptions in a @try /@catch block. According to the following example:

````objc
//self.service is and instance of CRCloudStorageProtocol implementations (Dropbox, GoogleDrive, Box, OneDrive)
  @try {
     //(OPTIONAL), specify where the authentication modal will be presented, in this example im using the navigation controller;

    //[self.service setTarget:self.navigationController];

    [self.service login]; // This line will explicitly trigger the login, without any other action
    
   // The login method is optional, actually if you perform ANY request and the service is not yet authenticated, it will present the authentication flow before executing the method.

  } @catch (NSException *exception) {
    //Catch the exception
    // Incase of the authentication or the method was not as excpected, treat the exception
  } @finally {
    //Finally Code
  }
````

 2 . CloudRail already does EXACTLY what you just wrote. To login just ONCE, you will need to perform the login the first time, and make use of the methods `saveAsString` and `loadAsString`.

````objc
CRDropbox * dropboxA = [[CRDropbox alloc] initWithClientId:@"ID" clientSecret:@"SECRET"];
  
[dropboxA login]; // explicitly requesting the login (you can use any other method)
NSString * authInfo = [dropboxA saveAsString];//this will return all the authentication info in string format.
  
/*You can persist the authInfo in the way that is more convenient to you, 
as long as you are able to retrieve it on another place/class/method*/
//--------------------------------------------------------------------------
//On another place/class/method
CRDropbox * dropboxB =  [[CRDropbox alloc] initWithClientId:@"ID" clientSecret:@"SECRET"];
[dropboxB loadAsString:authInfo];// provide the authentication info to the instance.
//from now on, the requests will NOT pop up the login screen again
````

**Comment by RWarnecke** [comment]
Hello @fel-cesar,

thank you for your feedback. To point 2 can I use the events saveAsString and loadAsString for all supported cloud drives or is that only a feature for dropbox ? And the second question is, where I need to save the authInfo string, save it automatically or must be saved it into the NSUserDefaults for example ?

**Comment by fel-cesar** [comment]
No problem @RWarnecke,

You can use `saveAsString` and `loadAsString` not just for **all CloudStorage** services, but for **all the services that uses authentication!** (e.g. Dropbox, Onedrive, Facebook, Twitter, etc...).

The answer to your second question, when you execute the method `saveAsString`,  you have the responsability to persist this string, either on NSUSerDefaults, CoreData, your own server, a file, anything that fits your needs, as long as you can safely and securely retrieve it later to use `loadAsString`.
