### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by Victorgf87** [CloudRail/cloudrail-si-ios-sdk#12]
Hello, I have just received, (and also just learnt to develop in iOS, so I'm a bit lost) a project that uses your framework.
When running it on a device, it shows an error that says
dyld: library not loaded: @rpath/CloudrailSI.framework/CloudRailSI
Referenced from: ...
Reason:image not found
It says "Thread 1: signal SIBART" in the window that shows some machine instructions
Could you tell me what's causing the error?
It's installed using pod, (version 3.3.1)
I have tried to add it on Embedded libraries, but it doesn't appear anywhere
I added pods_projectname.framework there and same stills happens

Thanks for your help

**Comment by fel-cesar** [comment]
Hello @Victorgf87 ,

Thank you for the feedback, is always nice to hear from the devs. We have some possible solutions for your issue.

* First I would *strongly* recommend you to improve to the latest version, since there is only improvements and benefits from doing so. In the time of this post the most recent is 4.2.0. The most recent is described by the shield: ![CocoaPods](https://img.shields.io/cocoapods/v/cloudrail-si-ios-sdk.svg)

* Make sure that you are loading the swift libraries. (Xcode8) Build settings -> BuildOptions -> Always Embed Swift Standard Libraries

* make sure you setup a CoudRail key (from 4.0 above)

If this doesnt solve your issue please provide more information like:
* cocoapods version
* Language (Swift2, Swift3, objective-C)
* How are you using the framework (method, structure, etc...)

You can always contact by support@cloudrail.com, so we can talk about more specific information.

**Comment by Victorgf87** [comment]
Sadly, I have to use Xcode 7.3.1, if I install your 4.2.0 it says "module file was created by a newer version of the compiler"

**Comment by Victorgf87** [comment]
I don't know how or why, but I reverted the project and ran it, and suddenly it works. I had done this a lot of times, so I don't understand anything... 
Thanks for your help anyways :)

**Comment by Victorgf87** [comment]
Sorry, I came back ;)

It suddenly started not working again. So I decided to risk it and migrated the project to Swift 3.
The error still happens, no matter what I try :(

 
>dyld: library not loaded: @rpath/CloudrailSI.framework/CloudrailSI
> Referenced from: /var/containers/Bundle/Application/3D6A2722-9794.../fashioncompass.app/fashioncompass
>Reason: Image not found

Maybe I should add some path to some step in the build system or something like that? (sorry, I am very new to iOS, and though I have been programming for almost 10 years now, I still don't get all of this configurations in compiled languages :( )

Cocoapods 1.1.1
Swift 3
I'm adding the framework via Pod, it used to work, but now it doesn't u_u 
I use your framework to Login via Facebook and Instagram. I can't be more specific since I didn't develop the project, and now I can't talk to the previous developer.

**Comment by Victorgf87** [comment]
BTW, if I go to my project target and try to add Cloudrail to linked frameworks or embedded library, it doesn't show anywhere, though all my other pods do. Is that normal?

**Comment by fel-cesar** [comment]
No problem @Victorgf87 we are here to help,
regarding the issue with "Image Not found issue", please give a look on our this wiki [page](https://documentation.cloudrail.com/ios/ios/FAQ#im-geting-the-image-not-found-error). 
Regarding the cocoapods issue, I will replicate the issue and check if there is any problem on our side, in any situation I will help you get the project running with CloudRail (Also will check the error on the linked framework import). Please tell me if the Image issue is solved with the link I sent you. I will reply ASAP when replicate and/or fix your issue. 

If you want to give more details about the project (to help the support), you can still contact by email support.

**Comment by Victorgf87** [comment]
Hey, @fel-cesar , thanks for your help. 
It wasn't your fault, it seems that the error appears "when your device is low on memory" (but it wasn't my case, so I don't know why), but I could fix it by changing required to optional.

However, I reseted the code (git reset) and it suddenly worked even without changing that to optional.

All of this must be some bug, but it makes me sick that it happens both on Xcode 7 and 8, and Internet is full of posts about this same problem, with no exact solution. So I wonder about how much Apple cares about their customers (customers, because we are paying a lot of money for this)
