### ISSUE TITLE
Module compiled with swift 3.0 cannot be imported in Swift 3.0.1

### ISSUE THREAD

**Issue by Radec43** [CloudRail/cloudrail-si-ios-sdk#13]
Hello there,
I am new in iOS development and i am very interest about your library but
i'm getting the following issue when i try to import CloudrailSI in my project and i don't know what to do.

**Comment by Radec43** [comment]
Hello there,
I am new in iOS development and i found very interesting in your library but
i'm getting the following issue when i try to import CloudrailSI in my project and i don't know what to do.

**Comment by fel-cesar** [comment]
Hello @Radec43 ,

We released an update with 3.0.1 support. Please let me know if the issue has been solved.
