### ISSUE TITLE
Swift Integration with CloudRail problem?

### ISSUE THREAD

**Issue by Sonezi** [CloudRail/cloudrail-si-ios-sdk#14]
After implementing login method for Facebook, i instantiate profile(CRFacebook) Object same as in documentation 

let facebook: ProfileProtocol = Facebook(clientId: "[clientID]", clientSecret: "[clientSecret]", redirectUri: "https://www.cloudrailauth.com/auth", state: "state")

in console i get profile object with data from Facebook.. My problem is i can't retrieve any data from it. I can't apply method saveAsString() or any other like getFullName().

<img width="1267" alt="screen shot 2016-11-14 at 16 16 57" src="https://cloud.githubusercontent.com/assets/18620537/20270543/c4b78a7a-aa87-11e6-9420-bb5b569f6e32.png">
<img width="1257" alt="screen shot 2016-11-14 at 16 29 46" src="https://cloud.githubusercontent.com/assets/18620537/20270544/c4b8e2e4-aa87-11e6-98b6-43bb3722e3d7.png">

**Comment by fel-cesar** [comment]
Hello @Sonezi ,
     At the moment you perform the first call over any instance of a CloudRail service the authentication flow should start automatically (e.g Example project). From the piece of code you provided seems like you are also using the FacebookSDK, the error you are getting , apparently is not related to CloudRail SDK, since we do not use `fbauth2` protocol internally, we use only `http` or `https`. According to the log, you still did not set the `LSApplicationQueriesSchemes` in your `info.plist`, this is because FBSDK uses different protocols in the authentication flow of the App. If you want deeper assistance you can also send an email to support@cloudrail.com (more freedom do discuss private pieces of the project).

Always good to have feedback.
