### ISSUE TITLE
Swift version 3.2.2

### ISSUE THREAD

**Issue by Victorgf87** [CloudRail/cloudrail-si-ios-sdk#18]
Hello, I have a problem, now I am getting an error
`Module compiled with Swift 4.0 cannot be imported in Swift 3.2.2: /Users/nabe/Documents/Projects/fashion-compass-ios/Pods/cloudrail-si-ios-sdk/Frameworks/CloudrailSI.framework/Modules/CloudrailSI.swiftmodule/x86_64.swiftmodule`
¿Could you tell me what version can I use for now to make it compatible?
Thanks in advance!

**Comment by riverbaymark** [comment]
@Victorgf87 I had asked about this and they have a new version about ready for primetime it seems.  They might be able to provide you a working version to try.

**Comment by Victorgf87** [comment]
Thanks for your message, @riverbaymark but what do you mean by primetime?

**Comment by riverbaymark** [comment]
Sorry for my slang terminology.  I just meant I think it’s ready to become part of their main package soon

**Comment by Victorgf87** [comment]
Oh, thanks for your answer, @riverbaymark I learnt something new :)

**Comment by mujtabaalamcr** [comment]
@Victorgf87 @riverbaymark 
We are working on this and hope to release a full version on Monday (20/11/17). 
Currently you can download the version that was built on XCode 9.1: https://www.dropbox.com/s/8ozj78m2co9dq17/CloudrailSI.framework.zip?dl=0

**Comment by fel-cesar** [comment]
Hey guys, ( @Victorgf87 and @riverbaymark ),

We`ve just released a small update that was compiled with the latest SDK, so you should not have this issue. Can you please confirm it?

**Comment by riverbaymark** [comment]
Hi guys,

I have been testing the framework for about a week (early peek) and it works great.  

Thanks!

Mark Pruitt FNP, Co-CEO
Riverbay Softworks LLC 
‭(415) 656-8617‬
www.riverbaysoftworks.com

**Comment by fel-cesar** [comment]
@riverbaymark, it's always nice to hear that! ;)
We will keep improving!
