### ISSUE TITLE
FB app domain error

### ISSUE THREAD

**Issue by rishi420** [CloudRail/cloudrail-si-ios-sdk#2]
Just downloaded the repo from git, opened in Xcode 7.2, changed facebookKey and facebookSecret. getting this error.

![simulator screen shot jun 19 2016 1 00 00 pm](https://cloud.githubusercontent.com/assets/2233857/16175924/fd143a16-3620-11e6-8870-3a820eca0ebd.png)

**Comment by FlorianWendel** [comment]
Hi there,
looks to me like the redirect URI is not properly configured in the app settings.
Have a look at: https://docs.cloudrail.com/docs/how-to-get-the-credentials#facebook

**Comment by rishi420** [comment]
Hi 
It solved my problem. 
Thanks 👍

**Comment by NuzhatPeerbits** [comment]
Hi team,

I had gone through the issue above issue(https://github.com/CloudRail/cloudrail-si-ios-sdk/issues/2) and same error I am getting in facebook login.

I had tried with the statement "Set the Redirect URI to 'https://www.cloudrailauth.com/auth'" which is given in the documentation for redirect URL but still getting the same error.

Xcode Version is 8.3.2
Swift version is swift 3.2

Hoping for the reply.

Thanks.

**Comment by mujtabaalamcr** [comment]
Hi Nuzhat,
I have test this and its working fine.
In your Facebook Developer account. Under PRODUCTS - Facebook Login / Settings make sure the 
**Client OAuth Login** and **Web OAuth Login** are **on**.
Under **Valid OAuth redirect URIs** use the URL https://www.cloudrailauth.com/auth if you are using the following constructor: 
**Facebook(clientId: "[Your App ID]", clientSecret: "[Your App Secret]")**

Thanks
