### ISSUE TITLE
Crash on demo app

### ISSUE THREAD

**Issue by kokitang** [CloudRail/cloudrail-si-ios-sdk#21]
Please check the screenshot and provide solutions.

<img width="868" alt="2017-12-01 11 28 56" src="https://user-images.githubusercontent.com/17448093/33466742-ec51237c-d68a-11e7-9df7-c6bc4b64ba53.png">

**Comment by fel-cesar** [comment]
Hello @kokitang,

Have you set up the variable ``kCloudRailAPIKey`` on the **AppDelegate.swift** file? You can get one on [cloudrail.com ](https://www.cloudrail.com) (after subscription). After setting up the CloudRail key, you will also need to setup the clientID and clientSecrets of the service you want to test in the **FoldersTableViewController.swift**.
