### ISSUE TITLE
Swift 4.0.3 and Xcode 9.2

### ISSUE THREAD

**Issue by RiverbayChris** [CloudRail/cloudrail-si-ios-sdk#22]
Can we please get the Swift4 branch built for Swift 4.0.3 / Xcode 9.2?

**Comment by fel-cesar** [comment]
@RiverbayChris, yes!
 We are currently working on an update that will also include the swift4 branch for swift 4.0.3. I will update here as soon as it is pushed and online.

**Comment by fel-cesar** [comment]
Latest Version is already using swift 4
