### ISSUE TITLE
Google Drive Logout

### ISSUE THREAD

**Issue by RiverbayChris** [CloudRail/cloudrail-si-ios-sdk#23]
Is there a way to force the sdk to use a UIWebView instead of SFSafariViewController?  There is no way to clear the cache for SFSafariViewController since it is shared system level.  Logouts for OAuth like Google Drive don't really log the user out, and they can get right back in without password with a single tap.

**Comment by RiverbayChris** [comment]
And apparently Google removed support for OAuth over UIWebView...  So is this an impossible scenario, or is there a way to actually log someone out of Google Drive so the password is required next time?

**Comment by RiverbayChris** [comment]
A workaround that I've discovered is to pop up a SFSafariViewController in the app upon logout, and route them to: 

"https://www.google.com/accounts/Logout?continue=https://appengine.google.com/_ah/logout?continue=https://www.example.com"

I don't think Google allows you to put in a custom URL scheme for that last "continue", so this is pretty ugly.

**Comment by fel-cesar** [comment]
@RiverbayChris, unfortunately with Google services (or any service that uses Google login) the developer is not allowed to use "embedded" browsers (aka UIWebView or WKWebView). Since we **HAVE** to use **SFSafariViewController** we cannot manage its cache to **programmatically** perform logout.

**Comment by fel-cesar** [comment]
@RiverbayChris , that can work. Its indeed not conventional. We are considering the option to add a method to our services to perform the logout, but the google services are blocking us. Considering all other services use embedded WebViews.

**Comment by RiverbayChris** [comment]
I will continue with the workaround, and set the kCloseSafariViewControllerNotification on a timer for now.  Thanks for looking into it!
