### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by RiverbayChris** [CloudRail/cloudrail-si-ios-sdk#24]
Is there a way to get at the access token?  I don't see it exposed anywhere, but I could be missing it.  I need it in order to support things that even the Advanced Request doesn't support, such as Google Drive's Team Drive feature, where I would need to add URL parameters.

**Comment by fel-cesar** [comment]
Hello @RiverbayChris ,
You can get the access token and other authentication relate values using the method ``saveAsString()``, it returns a JSON flavored string with the values used after the authentication. (access_token, refresh_token, expire_date, etc...)

**Comment by RiverbayChris** [comment]
Perfect, thanks.  Totally missed the wording (was looking for token property).

**Comment by fel-cesar** [comment]
This method was originally designed to be used along with the ``loadAsString()`` method, in order to avoid repeating the authentication process by the user. :)
( the token property can be a future implementation, again the problem for us is always the **uniformity** among all the services.
