### ISSUE TITLE
UI API called on a background thread

### ISSUE THREAD

**Issue by audioforge** [CloudRail/cloudrail-si-ios-sdk#26]
When I try to login to Dropbox, it seems the SDK calls the UI thread on a background.
This happens with the example app. Can we get an update of the SDK please?

Main Thread Checker: UI API called on a background thread: -[UIApplication keyWindow]
PID: 16816, TID: 1988206, Thread name: (none), Queue name: com.cloudrail.UnifiedCloudStorage, QoS: 0
Backtrace:
4   CloudrailSI                         0x000000010b20329c -[CRAwaitCodeRedirect topViewController] + 65
5   CloudrailSI                         0x000000010b203245 -[CRAwaitCodeRedirect currentViewController:] + 64
6   CloudrailSI                         0x000000010b202a60 -[CRAwaitCodeRedirect execute:parameters:] + 1731
7   CloudrailSI                         0x000000010b032447 -[CRInterpreter callFunction:parameters:] + 1197
8   CloudrailSI                         0x000000010b0ff6f0 -[CRDropbox login] + 391
9   Remaster                            0x000000010a8beaba __43-[ShowFilesTableViewController initService]_block_invoke + 170
10  libdispatch.dylib                   0x0000000111f5d2f7 _dispatch_call_block_and_release + 12
11  libdispatch.dylib                   0x0000000111f5e33d _dispatch_client_callout + 8
12  libdispatch.dylib                   0x0000000111f66855 _dispatch_queue_serial_drain + 1162
13  libdispatch.dylib                   0x0000000111f671ea _dispatch_queue_invoke + 336
14  libdispatch.dylib                   0x0000000111f62f7c _dispatch_queue_override_invoke + 733
15  libdispatch.dylib                   0x0000000111f6a102 _dispatch_root_queue_drain + 772
16  libdispatch.dylib                   0x0000000111f69da0 _dispatch_worker_thread3 + 132
17  libsystem_pthread.dylib             0x00000001124291ca _pthread_wqthread + 1387
18  libsystem_pthread.dylib             0x0000000112428c4d start_wqthread + 13

**Comment by fel-cesar** [comment]
Hello @audioforge , can you please try again with our latest version?
