### ISSUE TITLE
how can i get all  thumbnails ?

### ISSUE THREAD

**Issue by XJ-Code** [CloudRail/cloudrail-si-ios-sdk#28]
when i use ..

NSInputStream *inputStream = [_service thumbnailOfFileWithPath:path];
        inputStream.delegate = self;
        [inputStream scheduleInRunLoop:[NSRunLoop currentRunLoop] forMode:NSDefaultRunLoopMode];
        [inputStream open];

it will be crash on set delete antion.
reason : NSInvalidArgumentException', reason: '*** -setDelegate: only defined for abstract class.  Define -[CRBridgedInputStream setDelegate:]!'

**Comment by fel-cesar** [comment]
We've detected that was an issue while trying to **setDelegate** in the returned NSStream, we will release a fix ASAP. As for reading the content of the thumbnail, you can use the following snippet:

```objc
    NSMutableData * data = [NSMutableData data];
    NSInputStream * source = self;
    [source open];
    NSInteger result;
    uint8_t buffer[kBUFFER_LENGHT]; // BUFFER_LEN can be any positive integer, 1024 recommended
    while((result = [source read:buffer maxLength:kBUFFER_LENGHT]) != 0) {
      if(result > 0) {
        // buffer contains result bytes of data to be handled
        [data appendBytes:buffer length:result];
      } else {
        // The stream had an error. You can get an NSError object using [iStream streamError]
        if (result<0) {
          [NSException raise:@"STREAM_ERROR" format:@"%@", [source streamError]];
        }
      }
    }
  //Now you can convert the data to UIImage or manipulate it as you wish
```
