### ISSUE TITLE
CRUnknownException

### ISSUE THREAD

**Issue by XJ-Code** [CloudRail/cloudrail-si-ios-sdk#29]
when i can't  connect net work,the sdk will crash ,and tell me NSURLConnection finished with error - code -1200
when i click cancel ,it will also crash ,and tell me  user canceled

**Comment by fel-cesar** [comment]
I've just tested and could not replicate the "crash" if you click the cancel button, an exception is thrown (that should be captured). Also tested with no internet connection and the app does not crash, it simply does not load the web view (used in the authentication process). Are you wrapping the calls into a @try @catch block? 

```objc
CRDropbox * dropbox = [[CRDropbox alloc] initWithClientId:@"" clientSecret:@""];
  @try{
   [dropbox login];
    NSString * userLogin = [dropbox userLogin];
    NSLog(@"--%@--", userLogin);
  } @catch (NSException * exception){
    NSLog(@"--Exception thrown:%@--", exception.reason);
  }
```
