### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by AndrewSB** [CloudRail/cloudrail-si-ios-sdk#3]
Would be really awesome to get Carthage support

**Comment by fel-cesar** [comment]
Hello, we still working on general improvements and new ways to distribute the SDK. Carthage support is on our "TODO" list. Once available through Carthage it will be updated side by side with the pod. We will notify the users as soon as it is available.

**Comment by AndrewSB** [comment]
Gotcha, is that because the library is still not open source? I'm having trouble finding the actual source

**Comment by MattBolton** [comment]
Hi Andrew - The CloudRail libraries are not open source and we currently do not allow the community to make changes. One of our core value props is to ensure that the libraries are always up-to-date and that you as a developer don't have to worry anymore about changing APIs. In the free version here on GitHub, you actually have to trust us that we regularly update the library (what we do). If you need guarantees and required API change management, then we have product offerings for you. Just send me an email to matt@cloudrail.com if you are interested. Kind regards - Matt

**Comment by AndrewSB** [comment]
gotcha, thanks @MattBolton!
