### ISSUE TITLE
Module compiled with Swift 4.1.2 cannot be imported in Swift 4.2

### ISSUE THREAD

**Issue by victorcampeanu** [CloudRail/cloudrail-si-ios-sdk#32]
it is happening when developing with Xcode10.

if i manually add 4.1.2 toolchain then it builds but crashes at start

```
error: invalid value path 'symbols.clang-modules-cache-path'
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/286A9CFC-0747-438C-A2D1-8E527E6682B6/FileManager.app/Frameworks/CloudrailSI.framework/CloudrailSI
  Reason: Incompatible library version: CloudrailSI requires version 1.0.0 or later, but libswiftCore.dylib provides version 0.0.0
```

**Comment by victorcampeanu** [comment]
is anybody from your company bothering to make a build for swift 4.2? i guess i'm not the only one preferring to develop on Xcode 10

**Comment by fel-cesar** [comment]
Dear @victorcampeanu, a new version of the SDK for swift 4.2 is currently the current task in our roadmap. I will notify you as soon as it is released

**Comment by victorcampeanu** [comment]
@fel-cesar thank you!

**Comment by victorcampeanu** [comment]
but do not hurry so much, it's just beta 11..

**Comment by victorcampeanu** [comment]
2 months later and with Xcode 10 GM here, nobody took 5 minutes to recompile it... 👏

**Comment by RachenkoViacheslav** [comment]
Hi, can you say, when you release a new version of the SDK for swift 4.2? XCode 10 was released and my app start to show error Module compiled with Swift 4.1.2 cannot be imported in Swift 4.2

**Comment by fel-cesar** [comment]
The new version compiled with Xcode10, SDK of Swift4.2 has been released.
