### ISSUE TITLE
xcode10 reports missing symbol

### ISSUE THREAD

**Issue by audioforge** [CloudRail/cloudrail-si-ios-sdk#35]
Hi there,

When trying to run my project via Xcode10  on a real device, it spits out this: 
dyld: Symbol not found: __T0BOWV
  Referenced from: /private/var/containers/Bundle/Application/93354AB1-6E98-4F5B-B3AA-A2C196BBB9EA/Remaster.app/Frameworks/CloudrailSI.framework/CloudrailSI
  Expected in: /private/var/containers/Bundle/Application/93354AB1-6E98-4F5B-B3AA-A2C196BBB9EA/Remaster.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/93354AB1-6E98-4F5B-B3AA-A2C196BBB9EA/Remaster.app/Frameworks/CloudrailSI.framework/CloudrailSI

Might just be a simple recompile with Xcode 10 that would fix it?

Cheers,
T

**Comment by fel-cesar** [comment]
We are working on an update on iOS to also cover the new Xcode10, watch the repository and you will get notified as soon as it is released.

**Comment by GLiboni** [comment]
@fel-cesar: Any news?

**Comment by fel-cesar** [comment]
@GLiboni  and @audioforge , the new version compiled with Xcode10 and SDK of Swift 4.2 has been released.
