### ISSUE TITLE
Unable to install using the pod

### ISSUE THREAD

**Issue by hb2708** [CloudRail/cloudrail-si-ios-sdk#4]
@fel-cesar @felixkm 

I am trying to install sdk through pod but it gives the error
Contents of **POD** file.
```

platform :ios, '8.0'
use_frameworks!

target 'CloudRailDemo' do

pod 'cloudrail-si-ios-sdk'
end

```

Error given for pod install
`
[!] Unable to find a specification for `cloudrail-si-ios-sdk (~> 3.0.0)``

**Comment by felixkm** [comment]
Thanks for your question. We quickly tried it on ourself again and it seemed working. We'll elaborate that further and come back to you with a solution asap.

**Comment by hb2708** [comment]
Then am i doing something wrong or my cocoapods is having problem?

**Comment by fel-cesar** [comment]
e your cocoa pods **up to date**? We've tested again in different environments but couldn't **replicate** the error you are getting. Also, can you show us your pod file?
My current cocoa pods version is 1.0.1 and my pod file looks like this:
```ruby
target 'TestingCloudRailPodNative' do
   use_frameworks!
  pod "cloudrail-si-ios-sdk", '~> 3.0.0'
end
```

**Comment by hb2708** [comment]
Uninstalled and reinstalled cocoa pods 
Current version is same as yours 1.0.1
And it's working now

**Comment by hb2708** [comment]
I am closing this issue now
