### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by timbueno** [CloudRail/cloudrail-si-ios-sdk#5]
This library looks to be almost everything I've wanted for a long time.

Unfortunately it doesn't appear like the source is available. It may be difficult for me to use this library if I cannot absolutely depend on the continued development. Going open source goes a long way to this end.

If Dropbox changes their api again (along with any other service) and I've implemented features depending on this functionality - how can I be sure the library will be updated to support the changed api? If the library is open source I could at least edit the code myself.

Just a thought. It appears like you guys are VC funded so making the open source may not be in the cards. I'd really like to hear thoughts on this though.

Tim

**Comment by felixkm** [comment]
Hi Tim, 

thanks for reaching out. You are right, the CloudRail libraries are not open source and we currently do not allow the community to make changes. One of our core value props is to ensure that the libraries are always up-to-date and that you as a developer don't have to care about changing APIs. In the free version here on GitHub, you actually have to trust us that we regularly update the library (what we do). If you need guarantees and have that stated in a contract, we offer paid enterprise licenses. Just send me a quick mail to support@cloudrail.com if you are interested. 

Felix

**Comment by abhishmitra** [comment]
Hi,
Just wanted to understand, why did you discontinue with the Unified API project?
