### ISSUE TITLE
Support for Spotify Authentication!

### ISSUE THREAD

**Issue by cameronehrlich** [CloudRail/cloudrail-si-ios-sdk#7]

**Comment by fel-cesar** [comment]
It is a nice suggestion (and not the first one to ask for such authentication), we will discuss it as a new feature. Also will notify you when we decide to implement and release it.
Your feedback is always welcome.

**Comment by cameronehrlich** [comment]
Cool.

**Comment by cameronehrlich** [comment]
shoot.
