### ISSUE TITLE
The CloudrailSI seems not to be compiled with current version of swift compiler 

### ISSUE THREAD

**Issue by HildebKa** [CloudRail/cloudrail-si-ios-sdk#9]
Pods/cloudrail-si-ios-sdk/Frameworks/CloudrailSI.framework/CloudrailSI compiled with older version of Swift language (2.0) than previous files (3.0) for architecture armv7

Also get an error with the example project:
Get an error importing CloudrailSI into swift 3 app using Version 8.0 (8A218a)

Module file was created by an older version of the compiler; rebuild 'CloudrailSI' and try again: ..../cloudrail-si-ios-sdk-master/Example/Pods/cloudrail-si-ios-sdk/Frameworks/CloudrailSI.framework/Modules/CloudrailSI.swiftmodule/x86_64.swiftmodule

**Comment by fel-cesar** [comment]
Hi @HildebKa ,

We released a new compiled version on 4.1.0, can you please check if your issue has been solved? 
The official swift 3 version of the SDK is under development and you will be notified as soon as it is released.
